name: MATLAB Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "v2", "main" ]
  pull_request:
    branches: [ "v2", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        matlab-version: [r2020a, r2021a, r2022a, r2023a, r2025a]
        os: [ubuntu-latest, windows-latest, macos-latest]

        
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          version: ${{ matrix.matlab-version }}

      - name: Run MATLAB Tests
        uses: matlab-actions/run-tests@v2.1.2
        with:
          select-by-folder: tests